spring:
  datasource:
    username: root
#    password: root
    password: root@123456
#    url: jdbc:mysql://localhost:3306/vmm?useUnicode=true&characterEncoding=utf8
 #   url: jdbc:mysql://104.199.189.246:3306/vmm?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://104.199.189.246:3306/vmm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.zckj.vmms.vmms.entity
img:
  imagesPath: file:/D:/fileUpload/  #本地路径
#  imagesPath: file:/usr/images/  #服务器路径
#absoluteImgPath: D:/fileUpload/images/
#sonImgPath: /images/
server:
  port: 80
